### PR TITLE
Switch the background to an image of northern lights by Scott Rock

### PR DESCRIPTION
**Pull request by jviide**
The northern lights image is a resized and compressed version of an image by Scott Rock (https://unsplash.com/search/northern-lights?photo=mfSY12Au5o4).

Also switch the scanabc logo to a newer version.

### CODE REVIEW

**Comment by ikisusi** [comment]
Had originally two wishes for @nkapu with background picture. First one was that it would be a picture from someone involved in the company and there would be a story behind it. Second one was that it would be nice to have a summer picture with light while it is dark winter out here right now. :)

**Comment by jviide** [comment]
Ok. I'll close this and make a separate pull request for the updated logo only.

**Comment by evilon** [comment]
Scanned through my pics, didn't find anything useful yet which would match the presented wishes. 
I'll give it a second round a bit later.

Interestingly, I've always had just exactly the opposite picture in mind (vs summer & light). 
Dark outside, snow is raining almost horizontally and we are just going forward. The light comes from within, maybe from the desire to change things? And of course - Sisu! :) 

https://www.youtube.com/watch?v=kWg3BXjtJAo <- this video was going for that kind of mood and it received very nice feedback from more sunny parts of the world. :)

**Comment by jviide** [comment]
Ok, so something like this then?

screen shot 2016-11-25 at 16 19 54
screen shot 2016-11-25 at 16 19 26

😉

**Pull request closed without merging**
